package am.acba.components

enum class ComponentTypeEnum(val componentName: String) {
    BUTTONS("Buttons"),
    ALERTS("Alerts"),
    BADGES("Badges"),
    BANNERS("Banners"),
    CHIPS("Chips"),
    CONTROLS("Controls"),
    DIALOGS("Dialogs"),
    DIVIDER("Dividers"),
    DROP_DOWN("Drop downs"),
    EXCHANGE("Exchange"),
    INPUTS("Inputs"),
    LIST_ITEMS("List items"),
    TOOLBAR("Toolbar"),
    PHONE_NUMBER_INPUT("Phone number input"),
    CURRENCY_INPUT("Currency input"),
    EXPANDABLE_VIEW("Expandable view"),
    PRIMARY_TAB_LAYOUT("Primary Tab"),
    SEARCH_INPUT("Search input"),
    PIN_INPUT("Pin input"),
    QUICK_ACTION_AVATAR("Quick actions and avatar"),
    ONBOARDING_TOOTLTIPS("Onboarding tooltips"),
    CARD_LISTING("Card listing"),
    STATUS_SCREEN("Status screen"),
    BOTTOM_SHEET("Bottom sheet"),
    EMPTY_SCREEN("Empty screen"),
    PRODUCT_DESCRIPTION_CARD("Product description card"),
}